readux-ovservableを追加しました
sh1okoh/react-tutorial pull request #12
Opened 2019-09-04 00:47 UTC by sh1okoh

2019-09-04 03:44 UTC, hey-cube requested changes

2019-09-04 03:44 UTC, hey-cube commented on package.json
> +    "redux-aggregate": "^2.1.2",
あれ、前回の commit にこれ入ってなかったんでしたっけ？

2019-09-04 03:44 UTC, hey-cube commented on src/containers.js
> +      dispatch(gameCreators.jumpToPast(step)); // void
`// void` には何か意図がある感じです？

2019-09-04 03:52 UTC, sh1okoh commented on src/containers.js
> +      dispatch(gameCreators.jumpToPast(step)); // void
完全に削除忘れですね、、
背景として, jumpTo関数は空文字を返すということを聞いた時に、
メモとして残していただけです、、

2019-09-04 03:56 UTC, sh1okoh commented on package.json
> +    "redux-aggregate": "^2.1.2",
前回のコミットでも入っていたはずで、
今回ローカルで実行した時にreduxとかredux-aggregateモジュールがないぞ！と怒られたので、再度npm install したという背景があります。

2019-09-05 00:39 UTC, hey-cube approved these changes
![tumblr_inline_pk03u2XWUj1qa5y5a_500](https://user-images.githubusercontent.com/18608707/64303014-0883bd80-cfc1-11e9-8593-fc2975b26b92.gif)

2019-09-05 00:39 UTC, merged